### PR TITLE
Introduction of a new class "CleanCalendarEvent" to improve the look of the calendar

### PR DESCRIPTION
**Pull request by rwbr**
The goal of this changes is to improve the look of the calendar. This makes it necessary to introduce a new class for calendar events. These events need more properties than just a name and a 'isDone' parameter. The new class to be used for creating calendar events looks like this:

```dart
class CleanCalendarEvent {
  String summary;
  String description;
  String location;
  DateTime startTime;
  DateTime endTime;
  Color color;
  bool isAllDay;
  bool isDone;

  CleanCalendarEvent(this.summary,
      {this.description = '',
      this.location = '',
      this.startTime,
      this.endTime,
      this.color = Colors.blue,
      this.isAllDay = false,
      this.isDone = false});
}
```

Example entries then look like this:

```dart
final Map<DateTime, List<CleanCalendarEvent>> _events = {
    DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day): [
      CleanCalendarEvent('Event A',
          startTime: DateTime(DateTime.now().year, DateTime.now().month,
              DateTime.now().day, 10, 0),
          endTime: DateTime(DateTime.now().year, DateTime.now().month,
              DateTime.now().day, 12, 0),
          description: 'A special event',
          color: Colors.blue[700]),
    ],
    DateTime(DateTime.now().year, DateTime.now().month, DateTime.now().day + 2):
        [
      CleanCalendarEvent('Event B',
          startTime: DateTime(DateTime.now().year, DateTime.now().month,
              DateTime.now().day + 2, 10, 0),
          endTime: DateTime(DateTime.now().year, DateTime.now().month,
              DateTime.now().day + 2, 12, 0),
          color: Colors.orange),
      CleanCalendarEvent('Event C',
          startTime: DateTime(DateTime.now().year, DateTime.now().month,
              DateTime.now().day + 2, 14, 30),
          endTime: DateTime(DateTime.now().year, DateTime.now().month,
              DateTime.now().day + 2, 17, 0),
          color: Colors.pink),
    ],
  };
```

With this set of options ist is possible to color the dots in the day view according to the 'color' property of the event. Also the main application, that manages the map of events can reuse this object to create the event list for selected days. Then the new parameters 'summary', 'description', 'startTime' and 'endTime' com into play.

Simulator Screen Shot - iPhone 12 Pro - 2020-12-22 at 19 41 37

This is a  **breaking change**, so it must be well considered, if you want to merge it. Maybe you have a better idea to solve the underlying problem. And yes, I know that I could pass the calender a custom widget to make the day view look like I imagine, but I find this kind of inconvenient. It would be nice, if the calendar did this for the user. 

The need for this change arose through the development process of an app, where I planned to implement a calendar view based on this project.

### CODE REVIEW

**Review by pmcarlos — CHANGES_REQUESTED** [review]
I'm down to merge this and release as a new version mentioning the breaking change, this new class was indeed in the plans and has been previously requested
Could you please just fix your conflicts

**Comment by pmcarlos** [comment]
Really sorry for taken too long to check this, I've been really heads down on my job

**Comment by rwbr** [comment]
Don't mind. I'm happy if I could contribute.

**Comment by pmcarlos** [comment]
> Don't mind. I'm happy if I could contribute.

@rwbr do you mind please fixing the merge conflicts?

**Comment by rwbr** [comment]
I have fixed the conflicts. But it was only possible by putting all changes of PR #32, PR #36 and PR #37 in this merge. Could you please review the changes. If you merge the code and close this PR, then please also close the other ones (without merging).

**Comment by rwbr** [comment]
Did you already have a chance to review my contribution?

**Pull request merged**
